apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: vaultex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: nishajidla/vaultex-user:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: vaultex
spec:
  selector:
    app: user-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP